### ISSUE TITLE
Float should not be split

### ISSUE THREAD

**Issue by mkdreams** [go-ego/gse#114]
Split  “ loss of 76.7”.  I got "loss / of / 76 / . / 7", I want got "loss / of / 76 . 7".

What i can do?

- Gse version (or commit ref):v0.69.3
- Go version:1.16

**Comment by vcaesar** [comment]
The `seg.Cut(text)` and `seg.Cut(text, false)` is splited, `seg.Cut(text, true)` use the hmm mode, emm...

**Comment by mkdreams** [comment]
> The `seg.Cut(text)` and `seg.Cut(text, false)` is splited, `seg.Cut(text, true)` use the hmm mode, emm...

nice
