### ISSUE TITLE
add english Participles

### ISSUE THREAD

**Issue by naah69** [go-ego/gse#15]
1. Please speak English, this is the language everybody of us can speak and write.
2. Please take a moment to search that an issue **doesn't already exist**.
3. Please ask questions or config/deploy problems on our Gitter channel: https://gitter.im/go-ego/ego
4. Please give all relevant information below for bug reports, incomplete details will be handled as an invalid report.

**You MUST delete the content above including this line before posting, otherwise your issue will be invalid.**

- Gse version (or commit ref):
- Go version:
- Operating system and bit:
- Can you reproduce the bug at [Examples](https://github.com/go-ego/gse/tree/master/examples):
  - [ ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code: 

```Go

```
- Log gist:

## Description

...

**Comment by vcaesar** [comment]
Use `gse.AlphaNum = true`.
