### ISSUE TITLE
How to build without embed dictionary on Go1.16 or above?

### ISSUE THREAD

**Issue by AmazingRise** [go-ego/gse#154]
Hi,

I noticed that gse leads to a large binary size. After reviewing the code, I found the problem may lie [here](https://github.com/go-ego/gse/blob/a3176ceee465cb211785abbcd08c10c31fcadf02/dict_1.16.go#L25), which is caused by the embedded dictionary.

The program binary may vary, but the dictionary is relatively not changed. So is there a way to build a gse project without embedded dictionary?

Thanks.

- Gse version (or commit ref): 0.70.1
- Go version: 1.17
- Operating system and bit: Ubuntu 20.04 64bit
- Can you reproduce the bug at [Examples](https://github.com/go-ego/gse/tree/master/examples):
  - [x] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant

**Comment by vcaesar** [comment]
You can use `seg.LoadDict()`, and this function not used embedded dictionary.

**Comment by AmazingRise** [comment]
Thanks for your reply. But using `seg.LoadDict()` will also lead to a big binary. Because `dict_1.16.go` will always be compiled, along  with the super large embedded string `zh` and `ja`.

**Comment by vcaesar** [comment]
I tested in Macos and Ubuntu, but the build binary only 2.9M.

**Comment by AmazingRise** [comment]
> I tested in Macos and Ubuntu, but the build binary only 2.9M.

I've tested, too. Got the same result. It's my fault, for I thought it was an upstream bug related to `gse`.
I'd like to open a new issue in `gse-bleve`.

Thanks for your reply! Sorry for my fault.
