### ISSUE TITLE
分词能不能把符号和空格过滤掉

### ISSUE THREAD

**Issue by hyahm** [go-ego/gse#16]
分词用Slice 方法的时候， 都有符号和空格， 这东西对分词没用

**Comment by PyreneGitHub** [comment]
> 分词用Slice 方法的时候， 都有符号和空格， 这东西对分词没用

能介绍一下词性相关资料吗

**Comment by hyahm** [comment]
分词的话，  标点符号没用，  一般人搜索都是空格来分开的

**Comment by vcaesar** [comment]
Closed because of non-standard.

**Comment by alpiny** [comment]
use seg.Trim() to filter
----------------------------------
使用 seg.Trim()  可以过滤

**Comment by vcaesar** [comment]
目前增加停词和多种过滤方法
