### ISSUE TITLE
Why can't I load my user define dictionary?

### ISSUE THREAD

**Issue by RyanHuangNLP** [go-ego/gse#17]
```
seg.LoadDict("zh, /Users/xxxxxx/go/src/github.com/go-ego/gse/data/dict/dictionary.txt")
```
2019/07/18 10:40:48 Could not load dictionaries: " /Users/xxxxxx/go/src/github.com/go-ego/gse/data/dict/dictionary.txt", open  /Users/xxxxxx/go/src/github.com/go-ego/gse/data/dict/dictionary.txt: no such file or directory

**Comment by vcaesar** [comment]
"zh" is ".../go/src/github.com/go-ego/gse/data/dict/dictionary.txt", please use "," to split the dictionary, check your path.
