### ISSUE TITLE
English cut bug

### ISSUE THREAD

**Issue by Zrzzzz** [go-ego/gse#170]
- Gse version (or commit ref): 82fc9e4
- Go version: 1.20
- Operating system and bit: macOS 13.0
- Can you reproduce the bug at [Examples](https://github.com/go-ego/gse/tree/master/examples):
  - [x] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant

```Go
seg.LoadDict("zh")
seg.LoadDict("en")
seg.LoadDict("jp")
seg.LoadStop("zh")
logrus.Debugln(seg.CutSearch("Nowadays, there are more and more misunderstanding between parents and children which is so- called generation gap. It is estimated that ( 75 percentages of parents often complain their children’s unreasonable behavior while children usually think their parents too old fashioned )."))
```
- Log gist:

```
[nowadays ,   there   are   more   and   more   misunderstanding   between   parents   and   children   which   is   so -   called   generation   gap .   it   is   estimated   that   (   75   percentages   of   parents   often   complain   their   children ’ s   unreasonable   behavior   while   children   usually   think   their   parents   too   old   fashioned   ) .]
```

## Description

I read the data/en/dict.txt and find it empty. However, it seems like gse doesn't support english text cutting.

**Comment by vcaesar** [comment]
Are you read the README.md?

**Comment by Zrzzzz** [comment]
no english dict provided? I only see custom english dict. And it's said that it support english cutting?

**Comment by nitezs** [comment]
> no english dict provided? I only see custom english dict. And it's said that it support english cutting?

I'm also looking for a way to use gse for english word segmentation. Have you found an English dictionary yet?
