### ISSUE TITLE
使用过程中内存占用过高

### ISSUE THREAD

**Issue by wuzhix** [go-ego/gse#18]
我在使用的时候，发现内存占用过高，top里面有一半是这个包的占用。请问能优化下吗
Showing top 10 nodes out of 50
      flat  flat%   sum%        cum   cum%
   72.97MB 18.91% 18.91%    72.97MB 18.91%  github.com/go-ego/gse/vendor/github.com/go-ego/cedar.(*Cedar).addBlock
   60.51MB 15.68% 34.58%    60.51MB 15.68%  database/sql.convertAssign
   51.74MB 13.41% 47.99%   124.71MB 32.31%  github.com/go-ego/gse.(*Dictionary).addToken
   40.50MB 10.49% 58.48%    40.50MB 10.49%  github.com/go-ego/gse.splitTextToWords
   36.63MB  9.49% 67.97%    39.63MB 10.27%  sync.(*Map).Store
      27MB  7.00% 74.97%       27MB  7.00%  github.com/go-ego/gse.(*Segmenter).segmentWords
   21.50MB  5.57% 80.54%   337.34MB 87.41%  sensitive/task.LoadSensitive
   13.50MB  3.50% 84.04%    40.50MB 10.49%  github.com/go-ego/gse.(*Segmenter).CalcToken
   10.50MB  2.72% 86.76%       38MB  9.85%  sensitive/task.Analyze.func2.1
    7.50MB  1.94% 88.70%       13MB  3.37%  github.com/modern-go/reflect2.(*UnsafeSliceType).UnsafeMakeSlice

**Comment by vcaesar** [comment]
Closed because of non-standard. Reduce your dictionary file.
