### ISSUE TITLE
Invalid ranges produced on bad inputs

### ISSUE THREAD

**Issue by ValleZ** [go-ego/gse#2]
`segments := segmenter.Segment([]byte(w))`
`		for i, seg := range segments {`
`			if seg.End() > len(w) {`
`				log.Println("bad split: ", seg.Start(), "/", seg.End(), " w '", w, "' len ", len(w), "hex ", hex.EncodeToString([]byte(w)), "i ", i)`
`			} else {`
`				log.Println(w[seg.Start():seg.End()])`
`			}`
`		}`

The code above gives bad ranges on bad inputs, examples:
bad split:  3 / 6  w ' 缊 ' len  4 hex  01e7bc8a i  1
bad split:  5 / 8  w ' Vm犹 ' len  6 hex  566d01e78ab9 i  2
bad split:  5 / 8  w ' Vm犹 ' len  6 hex  566d01e78ab9 i  2
bad split:  3 / 6  w ' 榬 ' len  4 hex  01e6a6ac i  1

Expected behavior is that seg.End() should always be in range 0..len(w)

1) ego commit is recent, bdc71ec04efb0af77cf548eda828c001a76f3ae1
2) go version go1.9 windows/amd64

package main

import (
"flag"
"fmt"

"github.com/go-ego/gse"
	"encoding/hex"
	"log"
)

func main() {
	flag.Parse()
	var seg gse.Segmenter
	seg.LoadDict()
	text, _ := hex.DecodeString("01e7bc8a")
	segments := seg.Segment([]byte(text))
	fmt.Println(gse.ToString(segments, true))
	for _, seg := range segments {
		log.Println(text[seg.Start():seg.End()])
	}
}

2017/11/12 10:41:25 载入 gse 词典 C:/Users/Valle/go/src/github.com/go-ego/gse/data/dict/dictionary.txt
缊/zg 缊/zg 
2017/11/12 10:41:27 gse 词典载入完毕
2017/11/12 10:41:27 [1 231 188]
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.main()

**Comment by vcaesar** [comment]
Thanks for your suggesting, that the current version has not yet supported it.
