### ISSUE TITLE
"\001" in text gets error result

### ISSUE THREAD

**Issue by zhyon404** [go-ego/gse#31]
- Gse version (or commit ref):
1fd1428e78fe
- Go version:
1.14.2
- Operating system and bit:
any
- Can you reproduce the bug at [Examples](https://github.com/go-ego/gse/tree/master/examples):
  - [ ] No
  - [ ] Yes (provide example code)
  - [x] Not relevant
- Provide example code: 

```Go
func TestSegment(t *testing.T) {
	seg := &gse.Segmenter{}
	err := seg.LoadDict("../data/dictionary.txt")
	if err != nil {
		t.Fatal(err)
	}
	data := []byte("\001你好吗", )
	res := seg.Segment(data)
	for _, re := range res {
		t.Log(re.Token().Text())
		t.Log(re.Start())
		t.Log(re.End())
	}
}
```
- Log gist:
```

    TestSegment: process_test.go:51: 你
    TestSegment: process_test.go:52: 0
    TestSegment: process_test.go:53: 3
    TestSegment: process_test.go:51: 你好
    TestSegment: process_test.go:52: 3
    TestSegment: process_test.go:53: 9
    TestSegment: process_test.go:51: 吗
    TestSegment: process_test.go:52: 9
    TestSegment: process_test.go:53: 12
```

## Description

the first token should be "\001", we get second word instand.
the start of second token should be 1.

**Comment by vcaesar** [comment]
"\001" is " ", "\\001"?

**Comment by zhyon404** [comment]
> "\001" is " ", `"\\001"`?

intention is to cut "\001".

**Comment by vcaesar** [comment]
In the go, "\\" is the Escape symbol, you should use ``` "\\" ``` or ``` `\` ```.
