### ISSUE TITLE
Bleve

### ISSUE THREAD

**Issue by gedw99** [go-ego/gse#6]
Has anyone tried using this with bleve.

Bleve does this plus alot more but lacks decent Chinese / Japanese stemmers.

Using this with bleve would be a powerful stack

**Comment by vcaesar** [comment]
It is recommended to refer to [riot's](https://github.com/go-ego/riot) gse participle to using bleve.

**Comment by vcaesar** [comment]
Closed because it is currently unsure whether to add.

**Comment by gedw99** [comment]
bleve does facets and from what i saw riot does not.
facets are very powerful

**Comment by vcaesar** [comment]
I will consider joining it and welcome to contribute code.

**Comment by doutuiya** [comment]
any progress ?

**Comment by leopku** [comment]
I wrote Gse plugin for Bleve.
Repo is here: https://github.com/leopku/bleve-gse-tokenizer
