### ISSUE TITLE
Question: Is there any way to get segment info(not only string but with start and end) in hmm and search mode?

### ISSUE THREAD

**Issue by leopku** [go-ego/gse#68]
- Gse version (or commit ref):
0.60
- Go version:
1.14
- Operating system and bit:
macOS 10.14

## Description

In my case, I need get start and end info of each word after segmenting in hmm and search mode.
By reading apis, I only found:
* `CutSearch(string, true)` which only return []string but no star and end infos
* `Segment([]byte(text))` which can return segment with start and end info, but it does not accept param to choose search mode.

Is there anyway to something like `Segment([]byte(text), searchMode)`?

**Comment by vcaesar** [comment]
You can use `seg.ModeSegment([]byte(text), searchMode)`.

**Comment by leopku** [comment]
> ModeSegment

Thank you @vcaesar .
Sorry for my wrong words. 
Actually I want a method which returned something combines HMM and searchMode, for example `CutSearch` and `ModeSegment`.

**Comment by vcaesar** [comment]
The start and end of the search mode with HMM? It's not supported now, I will be supported in the near future.

**Comment by leopku** [comment]
Yep. 

I'm new to gse now. I'm glad to make a PR after I digging into this awesome project.

**Comment by leopku** [comment]
Hi there,

As of 0.63.1 released, did this issue fixed in the newest release?

**Comment by vcaesar** [comment]
Not yet, will be added soon.

**Comment by vcaesar** [comment]
You can use `seg.Analyze()` to get it.
