### ISSUE TITLE
请问字典里的分词频率是如何定义的？

### ISSUE THREAD

**Issue by JankinHou** [go-ego/gse#70]
请问分词字典里面的 分词频率 是如何定义和产生的？谢谢

**Comment by vcaesar** [comment]
中文词频是结巴分词根据语料库中词语出现的次数

如果你要添加新词，直接在 dict.txt 添加一行或者加载自定义词典就行; 有自己的语料库按语料库的频率添加, 没有的话可以写一个较小的整数就行了，比如 "3-10", 特殊词可以直接考虑特定的词频.
